name: Setup test script
description: 'Setup test script, should be called after checkout'
inputs:
  cache:
    default: ""
    description: 'Cache key for test bins'
  report:
    default: "false"
    required: false
    description: 'Report results'
  script:
    required: true
    description: 'Script to run'
  coverage:
    default: "false"
    required: false
    description: "Collect coverage"
  cache-python:
    default: "true"
    required: false
    description: "Cache python dependencies"
runs:
  using: 'composite'
  steps:
    - name: Setup testbin cache
      shell: bash
      if: ${{ runner.environment != 'github-hosted' }}
      run: |
        echo "TESTDATA_PATH=/opt/cache/testdata" >> $GITHUB_ENV

    - name: Install uv
      uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      with:
        working-directory: './scripts'

    - name: Add python dependencies
      shell: bash
      working-directory: ./scripts
      run: |
        uv sync

    - name: Cache test binaries
      if: ${{ inputs.cache != '' && runner.environment == 'github-hosted' }}
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ./scripts/bins
        key: testbins-${{ hashFiles('scripts/binaries.csv') }}-${{ inputs.cache }}-v2
        enableCrossOsArchive: true

    - name: Run script
      shell: bash
      working-directory: ./scripts
      run: uv run ${{ inputs.script }}

    - name: Report results
      if: ${{ inputs.report == 'true' }}
      shell: bash
      working-directory: ./scripts
      run: uv run python report.py
