name: Setup test script
description: 'Setup test script, should be called after checkout'
inputs:
  cache:
    default: ""
    description: 'Cache key for test'
  report:
    default: "false"
    required: false
    description: 'Report results'
  script:
    required: true
    description: 'Script to run'
  coverage:
    default: "false"
    required: false
    description: "Collect coverage"
  setup-python:
    default: "true"
    required: false
    description: "Setup Python"
runs:
  using: 'composite'
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - name: Setup Python
      if: ${{ inputs.setup-python == 'true' }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.13'
        check-latest: true
        cache: poetry

    - name: Add python dependencies
      shell: bash
      working-directory: ./scripts
      run: |
        poetry install

    - name: Cache test binaries
      if: ${{ inputs.cache != '' }}
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ./scripts/bins
        key: testbins-${{ hashFiles('scripts/binaries.csv') }}-${{ inputs.cache }}-v2
        enableCrossOsArchive: true

    - name: Run script
      shell: bash
      working-directory: ./scripts
      run: poetry run python ${{ inputs.script }}

    - name: Report results
      if: ${{ inputs.report == 'true' }}
      shell: bash
      working-directory: ./scripts
      run: poetry run python report.py
