name: Setup test script
description: 'Setup test script, should be called after checkout'
inputs:
  cache:
    default: ""
    description: 'Cache key for test bins'
  report:
    default: "false"
    required: false
    description: 'Report results'
  script:
    required: true
    description: 'Script to run'
  coverage:
    default: "false"
    required: false
    description: "Collect coverage"
  cache-python:
    default: "true"
    required: false
    description: "Cache python dependencies"
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: Zxilly/setup-uv@45f58ae383902bd64e09d003f17f638391b745d8
      with:
        enable-cache: ${{ inputs.cache-python }}
        prune-cache: ${{ inputs.cache-python }}

    - name: Add python dependencies
      shell: bash
      working-directory: ./scripts
      run: |
        uv sync

    - name: Cache test binaries
      if: ${{ inputs.cache != '' }}
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ./scripts/bins
        key: testbins-${{ hashFiles('scripts/binaries.csv') }}-${{ inputs.cache }}-v2
        enableCrossOsArchive: true

    - name: Run script
      shell: bash
      working-directory: ./scripts
      run: uv run python ${{ inputs.script }}

    - name: Report results
      if: ${{ inputs.report == 'true' }}
      shell: bash
      working-directory: ./scripts
      run: uv run python report.py
