codecov:
  allow_pseudo_compare: true
  allow_coverage_offsets: true
coverage:
  status:
    patch:
      default:
        target: 10%
        threshold: 10%
    project:
      default:
        threshold: 5%
        target: 70%

ignore:
  - "internal/wrapper/*.go"
  - "internal/knowninfo/dwarf_info.go"
  - "cmd/gsa/*.go"

comment:
  layout: "condensed_header, condensed_files, diff, flags, condensed_footer"
  behavior: default
  require_changes: false
  hide_project_coverage: true

flags:
  unit:
    carryforward: true
  integration:
    carryforward: true