codecov:
  allow_pseudo_compare: true
  allow_coverage_offsets: true
coverage:
  status:
    patch:
      default:
        target: 50%
        threshold: 10%
    project:
      default:
        threshold: 5%
        target: 70%

ignore:
  - "internal/wrapper/*.go"
  - "cmd/gsa/*.go"
