version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod-normal-deps:
        update-types:
          - patch
          - minor
      gomod-breaking-deps:
        update-types:
          - major

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    groups:
      ui-prod-deps:
        dependency-type: production
      ui-dev-deps:
        dependency-type: development

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    groups:
      pip-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"