version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - contextcheck
    - dupword
    - errorlint
    - gosec
    - loggercheck
    - mirror
    - nolintlint
    - revive
    - testifylint
    - thelper
    - usestdlibvars
  settings:
    gosec:
      excludes:
        - G115
    loggercheck:
      require-string-key: true
      no-printf-like: true
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: true
    revive:
      enable-all-rules: true
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: unhandled-error
          arguments:
            - fmt.Print.*
            - fmt.Fprint.*
            - bytes.Buffer.Write
            - bytes.Buffer.WriteByte
            - bytes.Buffer.WriteString
            - strings.Builder.WriteString
            - strings.Builder.WriteRune
        - name: cognitive-complexity
          arguments:
            - 300
          severity: warning
        - name: cyclomatic
          arguments:
            - 100
        - name: struct-tag
          disabled: true
        - name: add-constant
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: imports-blocklist
          disabled: true
        - name: nested-structs
          disabled: true
        - name: modifies-value-receiver
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: file-header
          disabled: true
        - name: empty-lines
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: false
formatters:
  enable:
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - prefix(syscall/js,unique,iter)
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
