# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - binary: gsa
    main: ./cmd/gsa
    ldflags:
      - "-s -w"
      - -X github.com/Zxilly/go-size-analyzer.version={{.Version}}
      - -X github.com/Zxilly/go-size-analyzer.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    flags:
      - "-trimpath"
      - "-pgo=default.pgo"
    tags:
      - embed

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: go-size-analyzer
    package_name: go-size-analyzer
    homepage: https://github.com/Zxilly/go-size-analyzer
    description: A tool for analyzing the dependencies in compiled Golang binaries, providing insight into their impact on the final build.
    maintainer: Zxilly <zxilly@outlook.com>
    license: AGPL-3.0-only
    formats:
      - apk
      - deb
      - rpm
      - archlinux

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"