name: Setup UI dependencies
description: 'Setup UI dependencies for linting and testing'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: '22'

    - name: Set up pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        package_json_file: 'ui/package.json'

    - name: Print pnpm version
      shell: bash
      run: pnpm --version

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install node dependencies
      shell: bash
      working-directory: ./ui
      run: |
        pnpm install --frozen-lockfile
