name: Build and publish bloaty binaries

on:
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build and release bloaty binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: google/bloaty
          submodules: recursive

      - name: Get commit hash and time
        id: commit
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_time=$(git show -s --format=%ci HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build

      - name: Build
        run: |
          cmake -B build -G Ninja -S .
          cmake --build build
          strip -s build/bloaty

      - name: Release binary
        uses: softprops/action-gh-release@v1
        with:
          files: build/bloaty
          prerelease: true
          name: Bloaty ${{ steps.commit.outputs.commit_time }}
          tag_name: bloaty
          body: |
            Commit: `${{ steps.commit.outputs.commit_hash }}`
            Commit time: `${{ steps.commit.outputs.commit_time }}`

