name: Goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-ui:
    uses: ./.github/workflows/build-ui.yml

  goreleaser:
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get tags
        run: git fetch --tags

      - uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: true
          check-latest: true

      - name: Download UI file
        uses: actions/download-artifact@v4
        with:
          name: ui

      - name: Move UI file
        run: mv index.html internal/ui/index.html

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}