name: Build UI

on:
  workflow_call:
    inputs:
      release:
        description: 'Make a release for the UI'
        type: boolean
        required: true
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  build-webui:
    name: Build Treemap WebUI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup UI dependencies
        uses: ./.github/actions/setup-ui-deps

      - name: Build
        working-directory: ./ui
        run: pnpm run build:ui
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          PULL_REQUEST_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Release
        if: ${{ inputs.release }}
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          artifactErrorsFailBuild: true
          allowUpdates: true
          artifactContentType: 'text/html'
          artifacts: 'ui/dist/webui/index.html'
          tag: ui-v1
          commit: master
          prerelease: true

      - name: Upload artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ui
          path: 'ui/dist/webui/index.html'


      