on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Rust Setup
        id: setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
        with:
          shared-key: ${{ runner.os }}-cargo-${{ steps.setup.outputs.cachekey }}

